// Code generated by gorest; DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/shopspring/decimal"
)

const handlerNameKey = "handler"

type ParamPlace int

const (
	UndefinedPlace ParamPlace = iota
	InBody
	InCookie
	InFormData
	InHeader
	InPath
	InQuery
)

type ContentType int

const (
	UndefinedContentType ContentType = iota
	AppJSON
	AppXML
	AppFormUrlencoded
	MultipartFormData
	TextPlain
)

type FieldError struct {
	In        ParamPlace
	BaseField string
	Message   string
	Reason    error
}

func NewFieldError(in ParamPlace, f string, msg string, err error) FieldError {
	return FieldError{
		In:        in,
		BaseField: f,
		Message:   msg,
		Reason:    err,
	}
}

func booleanConverter(input []string) (bool, error) {
	if len(input) == 0 {
		return false, fmt.Errorf("got empty value instead of boolean", input)
	}

	if len(input) > 1 {
		return false, fmt.Errorf("got array '%v' instead of boolean", input)
	}

	switch strings.ToLower(input[0]) {
	case "1", "true", "t":
		return true, nil
	case "0", "false", "f":
		return false, nil
	default:
		return false, fmt.Errorf("can't parse '%v' as boolean", input[0])
	}
}

func integerInt64Converter(input []string) (int64, error) {
	if len(input) != 1 {
		return 0, fmt.Errorf("got array '%v' instead of integer", input)
	}

	return strconv.ParseInt(input[0], 10, 64)
}

func integerInt32Converter(input []string) (int32, error) {
	if len(input) > 1 {
		return 0, fmt.Errorf("got array '%v' instead of integer", input)
	}

	v, err := strconv.ParseInt(input[0], 10, 32)
	return int32(v), err
}

func integerConverter(input []string) (int64, error) {
	return integerInt64Converter(input)
}

func numberFloatConverter(input []string) (float64, error) {
	if len(input) != 1 {
		return 0, fmt.Errorf("got array '%v' instead of integer", input)
	}

	return strconv.ParseFloat(input[0], 32)
}

func stringDateConverter(input []string) (time.Time, error) {
	if len(input) != 1 {
		return time.Time{}, fmt.Errorf("got array '%v' instead of string", input)
	}

	return time.Parse("2006-01-02", input[0])
}

func stringDateTimeConverter(input []string) (time.Time, error) {
	return stringDateConverter(input)
}

func stringYyyyMmDdConverter(input []string) (time.Time, error) {
	if len(input) != 1 {
		return time.Time{}, fmt.Errorf("got array '%v' instead of string", input)
	}

	return time.Parse("2006-01-02", input[0])
}

func stringUnixTimeConverter(input []string) (time.Time, error) {
	if len(input) != 1 {
		return time.Time{}, fmt.Errorf("got array '%v' instead of unix-time", input)
	}

	fromDateSec, err := strconv.ParseInt(input[0], 10, 64)
	if err != nil {
		return time.Time{}, err
	}

	return time.Unix(fromDateSec, 0), err
}

func stringEmailConverter(input []string) (string, error) {
	if len(input) != 1 {
		return "", fmt.Errorf("got array '%v' instead of string", input)
	}

	//TODO: write email check

	return input[0], nil
}

func stringBinaryConverter(input []string) ([]byte, error) {
	if len(input) != 1 {
		return []byte{}, fmt.Errorf("got array '%v' instead of string", input)
	}

	return []byte(input[0]), nil
}

func stringConverter(input []string) (string, error) {
	if len(input) != 1 {
		return "", fmt.Errorf("got array '%v' instead of string", input)
	}

	return input[0], nil
}

func integerDecimalConverter(input []string) (decimal.Decimal, error) {
	if len(input) > 1 {
		return decimal.Decimal{}, fmt.Errorf("got array '%v' instead of decimal", input)
	}

	return decimal.NewFromString(input[0])
}

func stringDecimalConverter(input []string) (decimal.Decimal, error) {
	if len(input) > 1 {
		return decimal.Decimal{}, fmt.Errorf("got array '%v' instead of decimal", input)
	}

	return decimal.NewFromString(input[0])
}

func ginGetCookie(c *gin.Context, param string) (string, bool) {
	cookie, err := c.Request.Cookie(param)
	if err == http.ErrNoCookie {
		return "", false
	}
	return cookie.Value, true
}

func __gin_get_parameter(c *gin.Context, in string, parameterName string) ([]string, bool, error) {
	if in == "cookie" {
		data, existed := ginGetCookie(c, parameterName)
		return []string{data}, existed, nil
	} else if in == "header" {
		data := c.Request.Header.Get(parameterName)
		return []string{data}, len(data) != 0, nil
	} else if in == "path" {
		data, existed := c.Params.Get(parameterName)
		return []string{data}, existed, nil
	} else if in == "query" {
		data, existed := c.Request.URL.Query()[parameterName]
		return data, existed, nil
	} else if in == "body" {
		data, existed := c.GetPostFormArray(parameterName)
		if existed == false && c.Request.MultipartForm != nil && c.Request.MultipartForm.File != nil {
			fhs, ok := c.Request.MultipartForm.File[parameterName]
			if !ok {
				return []string{}, ok, nil
			}

			return []string{fhs[0].Filename}, ok, nil
		}

		return data, existed, nil
	}

	return []string{}, false, fmt.Errorf("Unsupported 'in': %v", in)
}

type LeaderBoardService interface {
	// GET /leaderBoard
	GetLeaderBoard(in GetLeaderBoardRequest, c *gin.Context)

	// POST /results/:userId
	PostResults(in PostResultsRequest, c *gin.Context)

	// Service methods
	ProcessMakeRequestErrors(c *gin.Context, errors []FieldError)
	ProcessValidateErrors(c *gin.Context, errors []FieldError)
}

type LeaderBoardServiceServer struct {
	Srv LeaderBoardService
}

// _LeaderBoardService_GetLeaderBoard_Handler

type GetLeaderBoardRequest struct {
}

func (server LeaderBoardServiceServer) _LeaderBoardService_GetLeaderBoard_Handler(c *gin.Context) {
	c.Set(handlerNameKey, "GetLeaderBoard")

	var req GetLeaderBoardRequest

	server.Srv.GetLeaderBoard(req, c)
}

// _LeaderBoardService_PostResults_Handler

type PostResultsRequest struct {
	Body PostResultsRequestBody `json:"Body"`
	Path PostResultsRequestPath `json:"Path"`
}

type PostResultsRequestBody struct {
	JSON Points      `json:"JSON"`
	Type ContentType `json:"Type"`
}

type PostResultsRequestPath struct {
	UserID string `json:"userId"`
}

func (server LeaderBoardServiceServer) _LeaderBoardService_PostResults_Handler(c *gin.Context) {
	c.Set(handlerNameKey, "PostResults")

	var req PostResultsRequest
	dataPathUserID, _, err := __gin_get_parameter(c, "path", "userId")
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InPath, "-", "", err)})
		return
	}
	req.Path.UserID, err = stringConverter(dataPathUserID)
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InPath, "-", "", err)})
		return
	}

	contentType := c.Request.Header.Get("Content-Type")

	if contentType == "" {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InBody, "-", "unsupported Content-type", nil)})
		return
	}
	contentType = strings.Split(contentType, ";")[0]

	//TODO: refactor
	switch contentType {

	case "application/json":
		if err := json.NewDecoder(c.Request.Body).Decode(&req.Body.JSON); err != nil {
			server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InBody, "-", "can't decode body from JSON", err)})
			return
		}
	}
	server.Srv.PostResults(req, c)
}

// Router
func RegisterRoutes(r *gin.Engine, api LeaderBoardService) {
	e := &LeaderBoardServiceServer{api}

	r.Handle("GET", "/leaderBoard", e._LeaderBoardService_GetLeaderBoard_Handler)

	r.Handle("POST", "/results/:userId", e._LeaderBoardService_PostResults_Handler)
}

type HandlerRegister func(operationID, httpMethod, relativePath string, handler gin.HandlerFunc)

// CustomRouter
func RegisterRoutesCustom(handlerRegister HandlerRegister, api LeaderBoardService) {
	e := &LeaderBoardServiceServer{api}

	handlerRegister("GetLeaderBoard", "GET", "/leaderBoard", e._LeaderBoardService_GetLeaderBoard_Handler)

	handlerRegister("PostResults", "POST", "/results/:userId", e._LeaderBoardService_PostResults_Handler)
}

type Points decimal.Decimal

type UserPoints struct {
	Points Points `json:"points"`
	UserID string `json:"userId"`
}
type UserPointsArr []UserPoints
